SEBI/SebiMvc/Controllers/RadniNalogController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Infrastructure.EFModels;
using DomainServices;
using DomainModel;
using SebiMvc.Models;

namespace SebiMvc.Controllers
{
    public class RadniNalogController : Controller
    {
        private readonly SEBIContext _context;
        private readonly IRadniNalogRepository radniNalogRepository;
        private readonly IBiciklRepository biciklRepository;
        private readonly IServisRepository servisRepository;
        private readonly IStatusPoslaRepository statusPoslaRepository;
        private readonly IRadnikRepository radnikRepository;
        // private readonly IMapper mapper;

        public RadniNalogController(SEBIContext context,
                                     IRadniNalogRepository radniNalogRepository,
                                     IBiciklRepository biciklRepository,
                                     IServisRepository servisRepository,
                                     IStatusPoslaRepository statusPoslaRepository,
                                     IRadnikRepository radnikRepository/*,
                                     IMapper mapper*/)
        {
            _context = context;
            this.radniNalogRepository = radniNalogRepository;
            this.biciklRepository = biciklRepository;
            this.servisRepository = servisRepository;
            this.statusPoslaRepository = statusPoslaRepository;
            this.radnikRepository = radnikRepository;
            /*this.mapper = mapper*/;
        }

        // GET: RadniNalog
        public async Task<IActionResult> Index()
        {
            var data = await radniNalogRepository.GetRadniNalozi();
            // IList<RadninalogViewModel> radniNalozi = mapper.Map<IList<RadninalogViewModel>>(data);
            // ovo mozda padne zbog mapiranja StavkeNaloga
            // return View(radniNalozi);
            return View(data);
        }

        // GET: RadniNalog/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var radniNalog = await radniNalogRepository.GetRadniNalog(id);
            if (radniNalog == null)
            {
                return NotFound();
            }
            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            // return View(model);
            return View(radniNalog);
        }

        // GET: RadniNalog/Create
        public async Task<IActionResult> Create()
        {   
            ViewData["Idbicikl"] = new SelectList(await biciklRepository.GetBicikli(), nameof(DomainModel.Bicikl.Idbicikl), nameof(DomainModel.Bicikl.Nazbicikl));
            ViewData["Idservis"] = new SelectList(await servisRepository.GetServisi(), nameof(DomainModel.Servis.Idservis), nameof(DomainModel.Servis.Nazservis));
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus));
            ViewData["Izradio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme));
            return View();
        }

        // POST: RadniNalog/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DateTime Vrizrada, int Idservis, int Idosoba,int Izradio, int Idbicikl, int Idstatus)
        {
            if (ModelState.IsValid)
            {
                var id = await radniNalogRepository.CreateRadniNalog(
                    Vrizrada,
                    Idservis,
                    Idosoba,
                    Izradio,
                    Idbicikl,
                    Idstatus
                );
                return RedirectToAction(nameof(Edit), new { id = id });
            }

            ViewData["Idbicikl"] = new SelectList(await biciklRepository.GetBicikli(), nameof(DomainModel.Bicikl.Idbicikl), nameof(DomainModel.Bicikl.Nazbicikl), Idbicikl);
            ViewData["Idservis"] = new SelectList(await servisRepository.GetServisi(), nameof(DomainModel.Servis.Idservis), nameof(DomainModel.Servis.Nazservis), Idservis);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), Idstatus);
            ViewData["Izradio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme), Izradio);

            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            return View();
        }

        // GET: RadniNalog/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var radniNalog = await radniNalogRepository.GetRadniNalog(id);
            if (radniNalog == null)
            {
                return NotFound();
            }
            // ViewData["Idbicikl"] = radniNalog.Nazbicikl;
            // ViewData["Idosoba"] = radniNalog.PunoImeKorisnik;
            // ViewData["Idservis"] = radniNalog.NazServis;
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(),nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), radniNalog.Nazstatus);
            ViewData["Obavio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme), radniNalog.PunoImeObavio);
            
            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            // return View(model);
            return View(radniNalog);
        }

        // POST: RadniNalog/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Idradninalog, DateTime Vrpocetak, DateTime? Vrzavrsetak, int Idstatus, int? Obavio)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await radniNalogRepository.UpdateRadniNalog(Idradninalog,
                            Vrpocetak,
                            Vrzavrsetak,
                            Idstatus,
                            Obavio);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RadninalogExists(Idradninalog))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
                        
           
            RadniNalog radniNalog = await radniNalogRepository.GetRadniNalog(Idradninalog);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(),nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), radniNalog.Idstatus);
            ViewData["Obavio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme), radniNalog.Obavio);
        
            return View(radniNalog);
        }

        // GET: RadniNalog/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var radniNalog = await radniNalogRepository.GetRadniNalog(id);
            if (radniNalog == null)
            {
                return NotFound();
            }

            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            return View(radniNalog);
        }

        // POST: RadniNalog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await radniNalogRepository.DeleteRadniNalog(id);
            return RedirectToAction(nameof(Index));
        }

        private bool RadninalogExists(int id)
        {
          return (_context.Radninalogs?.Any(e => e.Idradninalog == id)).GetValueOrDefault();
        }
    }
}

SEBI/SebiMvc/Controllers/StavkaNalogController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Infrastructure.EFModels;
using DomainServices;
using DomainModel;
using SebiMvc.Models;

namespace SebiMvc.Controllers
{
    public class StavkaNalogController : Controller
    {
        private readonly SEBIContext _context;
        private readonly IStavkaNalogRepository stavkaNalogRepository;
        private readonly IRadRepository radRepository;
        private readonly IArtiklServisRepository artiklServisRepository;
        private readonly IStatusPoslaRepository statusPoslaRepository;


        public StavkaNalogController(SEBIContext context,
                                    IStavkaNalogRepository stavkaNalogRepository,
                                    IRadRepository radRepository,
                                    IArtiklServisRepository artiklServisRepository,
                                    IStatusPoslaRepository statusPoslaRepository
                                    )
        {
            _context = context;
            this.stavkaNalogRepository = stavkaNalogRepository;
            this.radRepository = radRepository;
            this.artiklServisRepository = artiklServisRepository;
            this.statusPoslaRepository = statusPoslaRepository;
        }


        public async Task<IActionResult> Create(int IdRadniNalog, int IdServis)
        {   
            ViewData["Idradninalog"] = IdRadniNalog;
            ViewData["Idservis"] = IdServis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad));
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(IdServis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl));
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus));

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, int Idradninalog, int Idservis, int Idstavkanalog, int Idrad, int Kolicinarad,
                                    int? Idartiklservis, int? Kolicinaartikl, int Idstatus)
        {
            if (ModelState.IsValid)
            {
                var idStavka = await stavkaNalogRepository.CreateStavkaNalog(Idradninalog,
                                                 Idstavkanalog,
                                                 Idrad,
                                                 Kolicinarad,
                                                 Idartiklservis,
                                                 Kolicinaartikl,
                                                 Idstatus);
                if (idStavka == -1) {
                    ViewData["ArtiklQError"] = "Nedovoljna količina artikla na skladištu!";
                } else {
                    return RedirectToAction(actionName: nameof(Edit), controllerName: nameof(RadniNalog), routeValues:new { id = Idradninalog });
                }                          
            }

            ViewData["Idradninalog"] = Idradninalog;
            ViewData["Idservis"] = Idservis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad), Idrad);
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(Idservis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl), Idartiklservis);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), Idstatus);

            return View();
        }

        public async Task<IActionResult> Edit(int id, int IdServis)
        {

            var stavkaNalog = await stavkaNalogRepository.GetStavkaNalog(id);
            if (stavkaNalog == null)
            {
                return NotFound();
            }

            ViewData["Idservis"] = IdServis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad));
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(IdServis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl));
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus));

            return View(stavkaNalog);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdRadniNalog, int IdServis, int Idstavka, int Idrad, int Kolicinarad,
                                             int? Idartiklservis, int? Kolicinaartikl, int Idstatus)
        {
 
            if (ModelState.IsValid)
            {   
                try
                {
                    var idStavka = await stavkaNalogRepository.UpdateStavkaNalog(Idstavka,
                                                                Idrad,
                                                                Kolicinarad,
                                                                Idartiklservis,
                                                                Kolicinaartikl,
                                                                Idstatus);
                    if (idStavka == -1) {
                        ViewData["ArtiklQError"] = "Nedovoljna količina artikla na skladištu!";
                    } else {
                        return RedirectToAction(actionName: nameof(Edit), controllerName: nameof(RadniNalog), routeValues : new { id = IdRadniNalog });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StavkaNalogExists(Idstavka))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }


            }

            ViewData["Idservis"] = IdServis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad), Idrad);
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(IdServis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl), Idartiklservis);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), Idstatus);
            StavkaNalog stavka = await stavkaNalogRepository.GetStavkaNalog(Idstavka);
            
            return View(stavka);
        }

        public async Task<IActionResult> Delete(int id)
        {

            var stavka = await stavkaNalogRepository.GetStavkaNalog(id);
            
            if (stavka == null)
            {
                return NotFound();
            }

            return View(stavka);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int IdRadniNalog)
        {
            if (_context.Stavkanalogs == null)
            {
                return Problem("Entity set 'SEBIContext.Stavkanalogs'  is null.");
            }

                await stavkaNalogRepository.DeleteStavkaNalog(id);
            
            
            return RedirectToAction(actionName: nameof(Edit), controllerName: nameof(RadniNalog), routeValues : new { id = IdRadniNalog });
        }

        private bool StavkaNalogExists(int id)
        {
          return (_context.Stavkanalogs?.Any(e => e.Idstavka == id)).GetValueOrDefault();
        }
    }
}

SEBI/SebiMvc/Views/RadniNalog/Create.cshtml
@model DomainModel.RadniNalog

@{
    ViewData["Title"] = "Create";
}

<h1>Dodavanje</h1>

<h4>Radni nalog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Vrizrada" class="control-label"></label>
                <input asp-for="Vrizrada" class="form-control" />
                <span asp-validation-for="Vrizrada" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Vrpocetak" class="control-label"></label>
                <input asp-for="Vrpocetak" class="form-control" />
                <span asp-validation-for="Vrpocetak" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrzavrsetak" class="control-label"></label>
                <input asp-for="Vrzavrsetak" class="form-control" />
                <span asp-validation-for="Vrzavrsetak" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Idservis" class="control-label"></label>
                <select asp-for="Idservis" class ="form-control" asp-items="ViewBag.Idservis">
                    <option value="" selected disabled>Odaberite servis</option>
                </select>
            </div>
            @* <div class="form-group">
                <label asp-for="Idosoba" class="control-label"></label>
                <select asp-for="Idosoba" class ="form-control" asp-items="ViewBag.Idosoba">
                    <option value="" selected disabled>Odaberite korisnika</option>
                </select>
            </div> *@
            <div class="form-group">
                <label asp-for="Izradio" class="control-label"></label>
                <select asp-for="Izradio" class ="form-control" asp-items="ViewBag.Izradio">
                    <option value="" selected disabled>Odaberite radnika</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Idbicikl" class="control-label"></label>
                <select asp-for="Idbicikl" class ="form-control" asp-items="ViewBag.Idbicikl">
                    <option value="" selected disabled>Odaberite bicikl</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Idstatus" class="control-label"></label>
                <select asp-for="Idstatus" class ="form-control" asp-items="ViewBag.Idstatus">
                </select>
            </div>
            @* <div class="form-group">
                <label asp-for="Obavio" class="control-label"></label>
                <select asp-for="Obavio" class ="form-control" asp-items="ViewBag.Obavio">
                </select>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="Index">Povratak na popis</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SEBI/SebiMvc/Views/RadniNalog/Delete.cshtml
@model DomainModel.RadniNalog

@{
    ViewData["Title"] = "Delete";
}

<h1>Brisanje</h1>

<h3>Jeste li sigurni da želite obrisati radni nalog?</h3>
<div>
    <h4>Radni nalog</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vrizrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vrizrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vrpocetak)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vrpocetak)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vrzavrsetak)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vrzavrsetak)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idbicikl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazbicikl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idosoba)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PunoImeKorisnik)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idservis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NazServis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idstatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazstatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Izradio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PunoImeIzradio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Obavio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PunoImeObavio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Idradninalog" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-outline-primary" asp-action="Index">Povratak na popis</a>
    </form>
</div>

SEBI/SebiMvc/Views/RadniNalog/Edit.cshtml
@model DomainModel.RadniNalog

@{
    ViewData["Title"] = "Edit";
}

<h1>Uređivanje</h1>

<h4>Radni nalog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idradninalog" />
            <div class="form-group">
                <label asp-for="Vrizrada" class="control-label"></label>
                <input asp-for="Vrizrada" class="form-control" disabled />
                <span asp-validation-for="Vrizrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrpocetak" class="control-label"></label>
                <input asp-for="Vrpocetak" class="form-control" />
                <span asp-validation-for="Vrpocetak" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrzavrsetak" class="control-label"></label>
                <input asp-for="Vrzavrsetak" class="form-control" />
                <span asp-validation-for="Vrzavrsetak" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NazServis" class="control-label"></label>
                <input asp-for="NazServis" class="form-control" disabled/>
                @* <span asp-validation-for="NazServis" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <label asp-for="PunoImeKorisnik" class="control-label"></label>
                <input asp-for="PunoImeKorisnik" class="form-control" disabled/>
                @* <span asp-validation-for="PunoImeKorisnik" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <label asp-for="PunoImeIzradio" class="control-label"></label>
                <input asp-for="PunoImeIzradio" class="form-control" disabled/>
                @* <span asp-validation-for="PunoImeIzradio" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <label asp-for="Nazbicikl" class="control-label"></label>
                <input asp-for="Nazbicikl" class="form-control" disabled/>
                @* <span asp-validation-for="Nazbicikl" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <label asp-for="Idstatus" class="control-label"></label>
                <select asp-for="Idstatus" class="form-control" asp-items="ViewBag.Idstatus"></select>
                <span asp-validation-for="Idstatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Obavio" class="control-label"></label>
                <select asp-for="Obavio" class="form-control" asp-items="ViewBag.Obavio">
                    <option value="" selected >Odaberite radnika</option>
                </select>
                <span asp-validation-for="Obavio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="d-flex justify-content-between">
    <a class="btn btn-outline-primary" asp-action="Index">Povratak na popis</a>
    <a class="btn btn-primary" asp-action="Create" asp-controller="StavkaNalog"
     asp-route-IdRadniNalog="@Model.Idradninalog" asp-route-IdServis="@Model.Idservis">Dodavanje stavke</a>
</div>

<hr />

<table class="table table-hover table-striped" id="stavke">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Stavke[0].Idstavka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stavke[0].Idrad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stavke[0].Kolicinarad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stavke[0].Idartiklservis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stavke[0].Kolicinaartikl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stavke[0].Idstatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Stavke) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Idstavka)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nazrad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kolicinarad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NazArtikl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kolicinaartikl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nazstatus)
            </td>
            <td>
                <a class="btn btn-warning" asp-action="Edit" asp-controller="StavkaNalog" asp-route-id="@item.Idstavka" asp-route-IdServis="@Model.Idservis">Uredi</a>
                <a class="btn btn-danger" asp-action="Delete" asp-controller="StavkaNalog" asp-route-id="@item.Idstavka">Obriši</a>
            </td>
        </tr>
}
    </tbody>
</table>


@section Styles {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css">

}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready( function () {
            $('#stavke').DataTable({
                language: {
                    search: "Pretraga",
                    info: "_START_ - _END_ (ukupno _TOTAL_)",
                    lengthMenu: "Prikaži _MENU_ zapisa",
                    paginate: {
                        first: "Prva",
                        previous: "Prethodna",
                        next: "Sljedeća",
                        last: "Zadnja"
                    },
                    emptyTable: "Nema podataka za prikaz",
                    info: "_START_ - _END_ od ukupno _TOTAL_ zapisa",
                    infoEmpty: "Nema podataka za prikaz",
                    infoFiltered: "(filtrirano od ukupno _MAX_ zapisa)",
                }
            });
        } );
    </script>
}