SEBI/SebiMvc/Models/StavkanalogViewModel.cs
using System;
using System.Collections.Generic;

namespace SebiMvc.Models;

public class StavkanalogViewModel
{
    public int Idstavka { get; set; }
    public int? Kolicinaartikl { get; set; }
    public int Kolicinarad { get; set; }
    public int Idradninalog { get; set; }
    public int Idrad { get; set; }
    public string Nazrad { get; set; } = null!;
    public int Idstatus { get; set; }
    public string Nazstatus { get; set; } = null!;
    public int? Idartiklservis { get; set; }
    public string NazArtikl { get; set; } = null!;
    public double Cijenakom { get; set; }


}

SEBI/SebiMvc/Controllers/RadniNalogController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Infrastructure.EFModels;
using DomainServices;
using DomainModel;
using SebiMvc.Models;

namespace SebiMvc.Controllers
{
    public class RadniNalogController : Controller
    {
        private readonly SEBIContext _context;
        private readonly IRadniNalogRepository radniNalogRepository;
        private readonly IBiciklRepository biciklRepository;
        private readonly IServisRepository servisRepository;
        private readonly IStatusPoslaRepository statusPoslaRepository;
        private readonly IRadnikRepository radnikRepository;
        // private readonly IMapper mapper;

        public RadniNalogController(SEBIContext context,
                                     IRadniNalogRepository radniNalogRepository,
                                     IBiciklRepository biciklRepository,
                                     IServisRepository servisRepository,
                                     IStatusPoslaRepository statusPoslaRepository,
                                     IRadnikRepository radnikRepository/*,
                                     IMapper mapper*/)
        {
            _context = context;
            this.radniNalogRepository = radniNalogRepository;
            this.biciklRepository = biciklRepository;
            this.servisRepository = servisRepository;
            this.statusPoslaRepository = statusPoslaRepository;
            this.radnikRepository = radnikRepository;
            /*this.mapper = mapper*/;
        }

        // GET: RadniNalog
        public async Task<IActionResult> Index()
        {
            var data = await radniNalogRepository.GetRadniNalozi();
            // IList<RadninalogViewModel> radniNalozi = mapper.Map<IList<RadninalogViewModel>>(data);
            // ovo mozda padne zbog mapiranja StavkeNaloga
            // return View(radniNalozi);
            return View(data);
        }

        // GET: RadniNalog/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var radniNalog = await radniNalogRepository.GetRadniNalog(id);
            if (radniNalog == null)
            {
                return NotFound();
            }
            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            // return View(model);
            return View(radniNalog);
        }

        // GET: RadniNalog/Create
        public async Task<IActionResult> Create()
        {   
            ViewData["Idbicikl"] = new SelectList(await biciklRepository.GetBicikli(), nameof(DomainModel.Bicikl.Idbicikl), nameof(DomainModel.Bicikl.Nazbicikl));
            ViewData["Idservis"] = new SelectList(await servisRepository.GetServisi(), nameof(DomainModel.Servis.Idservis), nameof(DomainModel.Servis.Nazservis));
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus));
            ViewData["Izradio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme));
            return View();
        }

        // POST: RadniNalog/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DateTime Vrizrada, int Idservis, int Idosoba,int Izradio, int Idbicikl, int Idstatus)
        {
            if (ModelState.IsValid)
            {
                var id = await radniNalogRepository.CreateRadniNalog(
                    Vrizrada,
                    Idservis,
                    Idosoba,
                    Izradio,
                    Idbicikl,
                    Idstatus
                );
                return RedirectToAction(nameof(Edit), new { id = id });
            }

            ViewData["Idbicikl"] = new SelectList(await biciklRepository.GetBicikli(), nameof(DomainModel.Bicikl.Idbicikl), nameof(DomainModel.Bicikl.Nazbicikl), Idbicikl);
            ViewData["Idservis"] = new SelectList(await servisRepository.GetServisi(), nameof(DomainModel.Servis.Idservis), nameof(DomainModel.Servis.Nazservis), Idservis);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), Idstatus);
            ViewData["Izradio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme), Izradio);

            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            return View();
        }

        // GET: RadniNalog/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var radniNalog = await radniNalogRepository.GetRadniNalog(id);
            if (radniNalog == null)
            {
                return NotFound();
            }
            // ViewData["Idbicikl"] = radniNalog.Nazbicikl;
            // ViewData["Idosoba"] = radniNalog.PunoImeKorisnik;
            // ViewData["Idservis"] = radniNalog.NazServis;
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(),nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), radniNalog.Nazstatus);
            ViewData["Obavio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme), radniNalog.PunoImeObavio);
            
            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            // return View(model);
            return View(radniNalog);
        }

        // POST: RadniNalog/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Idradninalog, DateTime Vrpocetak, DateTime? Vrzavrsetak, int Idstatus, int? Obavio)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await radniNalogRepository.UpdateRadniNalog(Idradninalog,
                            Vrpocetak,
                            Vrzavrsetak,
                            Idstatus,
                            Obavio);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RadninalogExists(Idradninalog))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
                        
           
            RadniNalog radniNalog = await radniNalogRepository.GetRadniNalog(Idradninalog);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(),nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), radniNalog.Idstatus);
            ViewData["Obavio"] = new SelectList(await radnikRepository.GetRadnici(), nameof(DomainModel.Radnik.Idradnik), nameof(DomainModel.Radnik.PunoIme), radniNalog.Obavio);
        
            return View(radniNalog);
        }

        // GET: RadniNalog/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var radniNalog = await radniNalogRepository.GetRadniNalog(id);
            if (radniNalog == null)
            {
                return NotFound();
            }

            // RadninalogViewModel model = mapper.Map<RadninalogViewModel>(radniNalog);

            return View(radniNalog);
        }

        // POST: RadniNalog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await radniNalogRepository.DeleteRadniNalog(id);
            return RedirectToAction(nameof(Index));
        }

        private bool RadninalogExists(int id)
        {
          return (_context.Radninalogs?.Any(e => e.Idradninalog == id)).GetValueOrDefault();
        }
    }
}

SEBI/SebiMvc/Controllers/StavkaNalogController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Infrastructure.EFModels;
using DomainServices;
using DomainModel;
using SebiMvc.Models;

namespace SebiMvc.Controllers
{
    public class StavkaNalogController : Controller
    {
        private readonly SEBIContext _context;
        private readonly IStavkaNalogRepository stavkaNalogRepository;
        private readonly IRadRepository radRepository;
        private readonly IArtiklServisRepository artiklServisRepository;
        private readonly IStatusPoslaRepository statusPoslaRepository;


        public StavkaNalogController(SEBIContext context,
                                    IStavkaNalogRepository stavkaNalogRepository,
                                    IRadRepository radRepository,
                                    IArtiklServisRepository artiklServisRepository,
                                    IStatusPoslaRepository statusPoslaRepository
                                    )
        {
            _context = context;
            this.stavkaNalogRepository = stavkaNalogRepository;
            this.radRepository = radRepository;
            this.artiklServisRepository = artiklServisRepository;
            this.statusPoslaRepository = statusPoslaRepository;
        }


        public async Task<IActionResult> Create(int IdRadniNalog, int IdServis)
        {   
            ViewData["Idradninalog"] = IdRadniNalog;
            ViewData["Idservis"] = IdServis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad));
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(IdServis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl));
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus));

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, int Idradninalog, int Idservis, int Idstavkanalog, int Idrad, int Kolicinarad,
                                    int? Idartiklservis, int? Kolicinaartikl, int Idstatus)
        {
            if (ModelState.IsValid)
            {
                var idStavka = await stavkaNalogRepository.CreateStavkaNalog(Idradninalog,
                                                 Idstavkanalog,
                                                 Idrad,
                                                 Kolicinarad,
                                                 Idartiklservis,
                                                 Kolicinaartikl,
                                                 Idstatus);
                if (idStavka == -1) {
                    ViewData["ArtiklQError"] = "Nedovoljna količina artikla na skladištu!";
                } else {
                    return RedirectToAction(actionName: nameof(Edit), controllerName: nameof(RadniNalog), routeValues:new { id = Idradninalog });
                }                          
            }

            ViewData["Idradninalog"] = Idradninalog;
            ViewData["Idservis"] = Idservis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad), Idrad);
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(Idservis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl), Idartiklservis);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), Idstatus);

            return View();
        }

        public async Task<IActionResult> Edit(int id, int IdServis)
        {

            var stavkaNalog = await stavkaNalogRepository.GetStavkaNalog(id);
            if (stavkaNalog == null)
            {
                return NotFound();
            }

            ViewData["Idservis"] = IdServis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad));
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(IdServis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl));
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus));

            return View(stavkaNalog);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdRadniNalog, int IdServis, int Idstavka, int Idrad, int Kolicinarad,
                                             int? Idartiklservis, int? Kolicinaartikl, int Idstatus)
        {
 
            if (ModelState.IsValid)
            {   
                try
                {
                    var idStavka = await stavkaNalogRepository.UpdateStavkaNalog(Idstavka,
                                                                Idrad,
                                                                Kolicinarad,
                                                                Idartiklservis,
                                                                Kolicinaartikl,
                                                                Idstatus);
                    if (idStavka == -1) {
                        ViewData["ArtiklQError"] = "Nedovoljna količina artikla na skladištu!";
                    } else {
                        return RedirectToAction(actionName: nameof(Edit), controllerName: nameof(RadniNalog), routeValues : new { id = IdRadniNalog });
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StavkaNalogExists(Idstavka))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }


            }

            ViewData["Idservis"] = IdServis;
            ViewData["Idrad"] = new SelectList(await radRepository.GetRadovi(), nameof(DomainModel.Rad.Idrad), nameof(DomainModel.Rad.Nazrad), Idrad);
            ViewData["Idartiklservis"] = new SelectList(await artiklServisRepository.GetArtikliServis(IdServis), nameof(DomainModel.ArtiklServis.Idartiklservis), nameof(DomainModel.ArtiklServis.Nazartikl), Idartiklservis);
            ViewData["Idstatus"] = new SelectList(await statusPoslaRepository.GetStatusiPosla(), nameof(DomainModel.Statusposla.Idstatus), nameof(DomainModel.Statusposla.Nazstatus), Idstatus);
            StavkaNalog stavka = await stavkaNalogRepository.GetStavkaNalog(Idstavka);
            
            return View(stavka);
        }

        public async Task<IActionResult> Delete(int id)
        {

            var stavka = await stavkaNalogRepository.GetStavkaNalog(id);
            
            if (stavka == null)
            {
                return NotFound();
            }

            return View(stavka);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int IdRadniNalog)
        {
            if (_context.Stavkanalogs == null)
            {
                return Problem("Entity set 'SEBIContext.Stavkanalogs'  is null.");
            }

                await stavkaNalogRepository.DeleteStavkaNalog(id);
            
            
            return RedirectToAction(actionName: nameof(Edit), controllerName: nameof(RadniNalog), routeValues : new { id = IdRadniNalog });
        }

        private bool StavkaNalogExists(int id)
        {
          return (_context.Stavkanalogs?.Any(e => e.Idstavka == id)).GetValueOrDefault();
        }
    }
}

SEBI/SebiMvc/Views/StavkaNalog/Create.cshtml
@model DomainModel.StavkaNalog

@{
    ViewData["Title"] = "Create";
}

<h1>Dodavanje nove stavke naloga</h1>

<h4>Stavka naloga</h4>
@if (@ViewBag.ArtiklQError != "")
{
    <h5 class="text-danger">@ViewBag.ArtiklQError</h5>

}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idradninalog" value="@ViewBag.Idradninalog"/>
            <div class="form-group">
                <label asp-for="Idrad" class="control-label"></label>
                <select asp-for="Idrad" class ="form-control" asp-items="ViewBag.Idrad">
                    <option value="" selected disabled>Odaberite uslugu</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Kolicinarad" class="control-label"></label>
                <input asp-for="Kolicinarad" class="form-control" min="1"/>
                <span asp-validation-for="Kolicinarad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idartiklservis" class="control-label"></label>
                <select asp-for="Idartiklservis" class ="form-control" asp-items="ViewBag.Idartiklservis">
                    <option value="" selected disabled>Odaberite artikl</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Kolicinaartikl" class="control-label"></label>
                <input asp-for="Kolicinaartikl" class="form-control" min="1"/>
                <span asp-validation-for="Kolicinaartikl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idstatus" class="control-label"></label>
                <select asp-for="Idstatus" class ="form-control" asp-items="ViewBag.Idstatus">
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" asp-route-IdServis="@ViewBag.Idservis"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="RadniNalog" asp-route-id="@ViewBag.Idradninalog">Povratak na nalog</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SEBI/SebiMvc/Views/StavkaNalog/Delete.cshtml
@model DomainModel.StavkaNalog
@{
    ViewData["Title"] = "Delete";
}

<h1>Brisanje</h1>

<h3>Jeste li sigurni da želite obrisati stavku naloga?</h3>
<div>
    <h4>Stavka naloga</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazrad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazrad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kolicinarad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kolicinarad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NazArtikl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NazArtikl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kolicinaartikl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kolicinaartikl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazstatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazstatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Idrad" />
        <input type="submit" value="Obriši" class="btn btn-danger" asp-route-IdRadniNalog="@Model.Idradninalog"/>
        <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="RadniNalog" asp-route-id="@Model.Idradninalog">Povratak na nalog</a>
    </form>
</div>

SEBI/SebiMvc/Views/StavkaNalog/Details.cshtml
@model DomainModel.Rad

@{
    ViewData["Title"] = "Details";
}

<h1>Detalji</h1>

<div>
    <h4>Usluga servisa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazrad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazrad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cijena)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.Idrad">Uredi</a>
    <a class="btn btn-outline-primary" asp-action="Index">Povratak na popis</a>
</div>

SEBI/SebiMvc/Views/StavkaNalog/Edit.cshtml
@model DomainModel.StavkaNalog

@{
    ViewData["Title"] = "Edit";
}

<h1>Uređivanje</h1>

<h4>Usluga servisa</h4>
@if (@ViewBag.ArtiklQError != "")
{
    <h5 class="text-danger">@ViewBag.ArtiklQError</h5>

}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Idradninalog"/>
            <input type="hidden" asp-for="Idstavka"/>
            <div class="form-group">
                <label asp-for="Idrad" class="control-label"></label>
                <select asp-for="Idrad" class ="form-control" asp-items="ViewBag.Idrad">
                    <option value="" selected disabled>Odaberite uslugu</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Kolicinarad" class="control-label"></label>
                <input asp-for="Kolicinarad" class="form-control" min="1"/>
                <span asp-validation-for="Kolicinarad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idartiklservis" class="control-label"></label>
                <select asp-for="Idartiklservis" class ="form-control" asp-items="ViewBag.Idartiklservis">
                    <option value="" selected disabled>Odaberite artikl</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Kolicinaartikl" class="control-label"></label>
                <input asp-for="Kolicinaartikl" class="form-control" min="1"/>
                <span asp-validation-for="Kolicinaartikl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idstatus" class="control-label"></label>
                <select asp-for="Idstatus" class ="form-control" asp-items="ViewBag.Idstatus">
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Spremi" class="btn btn-primary" asp-route-IdServis="@ViewBag.Idservis" asp-route-IdRadniNalog="@Model.Idradninalog"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="RadniNalog" asp-route-id="@Model.Idradninalog">Povratak na nalog</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}